### ISSUE TITLE
Label alignment for radio buttons and checkboxes

### ISSUE THREAD

**Issue by ricklambrechts** [minvws/nl-rdo-manon#139]
The labels are not correct aligned.

![image](https://user-images.githubusercontent.com/1367665/231164905-c23ec531-78a2-4b69-b152-7f05d42fcbde.png)

**Comment by HeleenSG** [comment]
Solved. For more information see:

https://minvws.github.io/nl-rdo-manon/documentation/components/radio-button.html

and: 

https://minvws.github.io/nl-rdo-manon/documentation/components/checkbox.html
