### ISSUE TITLE
Breadcrumb bar icon missing 

### ISSUE THREAD

**Issue by ricklambrechts** [minvws/nl-rdo-manon#260]
![image](https://github.com/minvws/nl-rdo-manon/assets/1367665/77330eb7-2a1c-4b89-a938-10ca2b26b8ee)

It is currently not possible to set font-family for breadcrumb-bar-icon.

**Comment by HeleenSG** [comment]
Solved in: https://github.com/minvws/nl-rdo-manon/pull/284
