### ISSUE TITLE
Style button icon:before

### ISSUE THREAD

**Issue by ricklambrechts** [minvws/nl-rdo-manon#348]
We need to style button icon:before.

![image](https://github.com/minvws/nl-rdo-manon/assets/1367665/b39230ab-537a-4703-b950-bf21dcf15767)

```html
<a href="https://example.nl/create" class="button"><span class="icon icon-user"></span> Nieuwe organisatie aanmaken</a>
```

**Comment by reinschaap** [comment]
Solution might be similar to the solution needed for https://github.com/minvws/nl-rdo-manon/issues/422

**Comment by ppvg** [comment]
Closing this in favor of https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme/issues/485.
