### ISSUE TITLE
Expando rows in Manon triggers default form submission 

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-rdo-manon#355]
There are many place where expando-rows are used to show extra info in dropdown box:

<img width="1333" alt="image" src="https://github.com/minvws/nl-kat-coordination/assets/30832687/d9b862da-f173-4b0d-a5e2-44e465269630">

` <button
                                                    class="expando-button"
                                                    data-icon-open-class="icon ti-chevron-down"
                                                    data-icon-close-class="icon ti-chevron-up"
                                                    data-close-label="{% translate "Close details" %}">
                                                {% translate "Open details" %}
                                            </button>`

The dropdown works good when it is outside a form

Issue: When the expando rows are included in a form element, it will automatically trigger form submission.

How to solve this problem? 
Because the expando-rows is defined as a button an no type is defined it will automatically set type="submit" 

Put type="button" on the expando-rows class button

`<button type="button"></button>`

**Comment by underdarknl** [comment]
as specified in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type the default becomes submit for unset button types.
Another solution could be to call preventDefault() on the click events.
