### ISSUE TITLE
Add `display: flex` to accordion item toggle buttons

### ISSUE THREAD

**Issue by vvandijck** [minvws/nl-rdo-manon#368]
### Describe the bug, issue or concern

By default, the accordion item button does not have `display: flex;` set, but it does have flexbox properties set which in turn are not applied. Please add `display: flex;` by default so all flexbox properties are also applied. See screenshots for the difference.

**Currently: no `display: flex;` set:**

![Scherm­afbeelding 2023-06-30 om 11 37 44](https://github.com/minvws/nl-rdo-manon/assets/12752012/11aab0b8-d7cd-4710-b6f5-acbea6158c0a)

**Desired: with `display: flex;` set:**

![Scherm­afbeelding 2023-06-30 om 11 37 31](https://github.com/minvws/nl-rdo-manon/assets/12752012/b014786c-a140-4098-b759-8ab3f251fb1e)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by HeleenSG** [comment]
Yes, good point. Thanks for adding this as a ticket. The button styling within accordions need some attention. 

Unfortunately buttons can't be flex containers as this isn't supported and will lead to unexpected and unwanted behaviour. As we've seen happen recently with testing.

Some info on the matter: 
"Certain HTML elements, like <summary>, <fieldset> and <button>, do not work as flex containers. The browser's default rendering of those element's UI conflicts with the display: flex declaration.
Demo [9.1.a](https://philipwalton.github.io/flexbugs/9.1.a-bug.html) shows how <button> elements didn't work in Firefox, and demo [9.2.a](https://philipwalton.github.io/flexbugs/9.2.a-bug.html) shows that <fieldset> elements don't work in most browsers. Demo [9.3.a](https://philipwalton.github.io/flexbugs/9.3.a-bug.html) shows that <summary> elements dont work in Safari."

https://github.com/philipwalton/flexbugs
