### ISSUE TITLE
Input field placeholder text

### ISSUE THREAD

**Issue by ppvg** [minvws/nl-rdo-manon#435]
From independent accessibility report, SC 3.3.2:

<blockquote lang="nl">
Op pagina <a href="https://minvws.github.io/nl-rdo-manon/documentation/components/form-input-textarea.html">components/form-input-textarea.html</a> staat een invoerveld. Het label hierbij is "Bericht". In de placeholdertekst staat nu "Jouw vraag op opmerking". Deze placeholdertekst geeft aanvullende informatie over wat er van de gebruiker verwacht wordt, maar deze informatie verdwijnt als een gebruiker iets gaat invullen. Het is niet de bedoeling om aanvullende instructies in de placeholdertekst te plaatsen. Zorg ervoor dat instructies of richtlijnen altijd beschikbaar zijn.
</blockquote>

Input fields in the docs should not use placeholder text, and the docs should advise against their use.

**Comment by underdarknl** [comment]
https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research
