### ISSUE TITLE
Theme documentation

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-rdo-manon#562]
Add documentation describing how a theme can be made and used within projects. 

Points of attention:
- Header examples (Component examples where multiple styles may be available within one theme, which use the same Manon-component but different styling.)
- How to start
- Structure

**Comment by HeleenSG** [comment]
Not specific enough for a ticket. It's too large.

**Comment by reinschaap** [comment]
Niet meenemen / laten afhangen van de architectuur keuzes van Manon

**Comment by HeleenSG** [comment]
Meegenomen binnen het documentatie-overzicht: 
https://nextcloud.irealisatie.nl/apps/files/files/437731?dir=/iCore/Manon&openfile=true
