### ISSUE TITLE
Remove `auditConfig` when `elliptic` CVEs are resolved. 

### ISSUE THREAD

**Issue by ppvg** [minvws/nl-rdo-manon#615]
Currently the `package.json` includes an `auditConfig` (added in #614) to ignore the CVEs https://github.com/advisories/GHSA-49q7-c7j4-3p7m, https://github.com/advisories/GHSA-977x-g7h5-7qgw and https://github.com/advisories/GHSA-f7q4-pwc6-w24p. These are all for the `elliptic` package, which is a dev-only dependency of one of our example app (which doesn't run in CI and is not a dependency for the published npm packages).

The `auditConfig` can be removed as soon as these CVEs are resolved or the `laravel-mix` example app is removed.

**Comment by gerbrand-bosch** [comment]
It looks like it's resolved in https://github.com/indutny/elliptic/releases/tag/v6.5.7.

**Comment by ppvg** [comment]
> It looks like it's resolved in https://github.com/indutny/elliptic/releases/tag/v6.5.7.

Yup, now two more things need to happen before we can remove the `auditConfig`:
1. the three advisories need to be updated to flag 6.5.7 as not vulnerable, and
2. either:
  a. all dependencies in the chain (as listed in the result of `pnpm audit`, see below) need to be updated, or
  b. we can add an [`pnpm.overrides`](https://pnpm.io/package_json#pnpmoverrides) to force the use of elliptic 6.5.7.

<details>
<summary>The result of <code>pnpm audit</code></summary>
                                                                  main
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ low                 │ Elliptic's ECDSA missing check for whether leading bit │
│                     │ of r and s is zero                                     │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ elliptic                                               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=2.0.0 <=6.5.6                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ <0.0.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ browserify-sign@4.2.3 > elliptic@6.5.5                 │
│                     │                                                        │
│                     │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ create-ecdh@4.0.4 > elliptic@6.5.5                     │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-977x-g7h5-7qgw      │
└─────────────────────┴────────────────────────────────────────────────────────┘
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ low                 │ Elliptic's EDDSA missing signature length check        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ elliptic                                               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=4.0.0 <=6.5.6                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ <0.0.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ browserify-sign@4.2.3 > elliptic@6.5.5                 │
│                     │                                                        │
│                     │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ create-ecdh@4.0.4 > elliptic@6.5.5                     │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-f7q4-pwc6-w24p      │
└─────────────────────┴────────────────────────────────────────────────────────┘
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ low                 │ Elliptic allows BER-encoded signatures                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ elliptic                                               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=5.2.1 <=6.5.6                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ <0.0.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ browserify-sign@4.2.3 > elliptic@6.5.5                 │
│                     │                                                        │
│                     │ examples/laravel-mix > laravel-mix@6.0.49 >            │
│                     │ node-libs-browser@2.2.1 > crypto-browserify@3.12.0 >   │
│                     │ create-ecdh@4.0.4 > elliptic@6.5.5                     │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-49q7-c7j4-3p7m      │
└─────────────────────┴────────────────────────────────────────────────────────┘
3 vulnerabilities found
Severity: 3 low
</detail>

Since these are dev-only dependencies, isolated to the example app, I think we can wait. :)
